wallpaper {
    monitor = HDMI-A-1
    path = /home/niels/Downloads/pjvic9eq4vt41.jpg
    fit_mode = cover
  }
wallpaper {
    monitor = DP-2
    path = /home/niels/Downloads/pjvic9eq4vt41.jpg
    fit_mode = cover
  }
